In [5]:
import numpy

# Demonstrating the dot Product
"""
Rules:

The number of columns in the first array must be the same as the number of rows in the second array

If the first array has dimensions nxm (n rows, m columns) and the second has dimensions mxq (m rows, q columns)

The dot product will have dimensions n x q

"""

a=[[1,2],[3,4],[5,6]]
b=[[7,8,9],[10,11,12]]

A= numpy.array(a)
B= numpy.array(b)
C=numpy.dot(A,B)
print(C)

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


In [8]:
A.shape
B.shape

(2, 3)